### PR TITLE
Get rid of Python2

### PR DESCRIPTION
**Pull request by eli-osherovich**
### PR Overview

- [n] This PR requires new unit tests [y/n] (make sure tests are included)
- [n] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

Removed Python2 code because `keras_preprocessing` is incompatible with Python2 anymore.

### CODE REVIEW

**Comment by Dref360** [comment]
We should remove https://github.com/keras-team/keras-preprocessing/blob/master/tests/test_documentation.py#L166

as well.

**Comment by eli-osherovich** [comment]
I think I removed it.

**Comment by Dref360** [comment]
Oh right, my bad.

**Review by Dref360 — APPROVED** [review]
LGTM

**Pull request merged**
