### PR TITLE
adding gaussian noise

### PR DESCRIPTION
**Pull request by woolfel**
I wanted to add noise to the training images, but keras didn't have it,
so I decided to implement it

### PR Overview

- [ ] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by woolfel** [comment]
The image_test.py file is quite big. I'm not sure where to add the test case. I tested it manually. attached is example of the original image and noised image.
noised
image00

**Comment by Dref360** [comment]
In the literature, adding Gaussian noise is not widely used, so I don't see the use case for this feature.

**Comment by woolfel** [comment]
Ok. I can understand why gaussian isn't widely used for things like MNIST or Fashion MNIST. For training faster_rcnn_resnet101 I manually added gaussian noise in Photoshop, which is a tedious manual process. It did reduce overfitting on RGB images larger than 160x120. Thanks for reviewing it, I find it useful so I'll keep in my fork.

**Comment by fchollet** [comment]
Closing outdated PR. Note that the Keras Preprocessing repository is no longer in use, instead please just use the dataset utilities provided in `tf.keras.utils` ([see docs](https://keras.io/api/data_loading/)).

**Pull request closed without merging**
