### PR TITLE
added tiff as an extension for listing images

### PR DESCRIPTION
**Pull request by elmerehbi**

### CODE REVIEW

**Comment by Dref360** [comment]
This looks like deadcode to me? Should we just deprecate it?
What's your usecase to keep it?

We could keep it but we would need to add tests and docs.

**Comment by elmerehbi** [comment]
@Dref360 Why deadcode? No one  is using tiff?

My use case is loading 16bit tiff (grayscale satellite) images.

Is there a better way?

**Comment by Dref360** [comment]
I was talking about the fact that list_pictures is not used anywhere in the codebase.

**Comment by elmerehbi** [comment]
@Dref360 Ah I didn't notice that. I am not using it either (using PIL instead) but thought it would be a good addition. However following your comment then I agree.

**Pull request closed without merging**
