### PR TITLE
add ignore_class_split option for non categorical labels in image data generator

### PR DESCRIPTION
**Pull request by rugggg**
### Summary
Add option to handle non categorical labels when using NumpyArrayIterator/ImageDataGenerator.flow and a validation split. This is useful in non classification problems like pose estimation where the target Y is in a continuous space.

### Related Issues
#214 
### PR Overview

- [y] This PR requires new unit tests [y/n] (make sure tests are included)
- [y] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by beeb** [comment]
What's the status on this?

**Comment by Dref360** [comment]
Oh I totally missed that one. Sorry for that.

Yes I think we can add something like that. Maybe a "strict" mode?

**Comment by rugggg** [comment]
> Oh I totally missed that one. Sorry for that.
> 
> Yes I think we can add something like that. Maybe a "strict" mode?
> 
> In any cases, this PR requires more tests.
@Dref360  - Happy to add the needed tests, what do you see that needs to be added?

**Comment by Dref360** [comment]
I would merge if you can fix the conflicts.

**Comment by rugggg** [comment]
@Dref360 merge conflicts are fixed and all tests passing, let me know if you see other things to fix

**Pull request merged**
