### PR TITLE
Set matrix center correctly

### PR DESCRIPTION
**Pull request by eli-osherovich**
Matrix center was set incorrectly (one off). To correct either call transform_matrix_offset_center() with h-1 ,w-1. Or  fix the sign inside that function and continue using h and w (more intuitive).

### PR Overview

- [n] This PR requires new unit tests [y/n] (make sure tests are included)
- [n] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by Dref360** [comment]
Could we add a test to be sure that the matrix is rightly centered?

**Comment by eli-osherovich** [comment]
@Dref360 Do you mean a unit test or the way to know wither + or - is correct?

Here is a simple example:
```python
img = np.expand_dims(np.array([[0, 1], [0, 0]]), -1)
tf.keras.preprocessing.image.apply_affine_transform(img, theta=90)

array([[[0],
        [0]],

       [[0],
        [0]]])
```

**Comment by Dref360** [comment]
Yes so that if we modify this portion of the code again, we won't merge the same bug.

**Comment by eli-osherovich** [comment]
Added a unit test.

P. S. 
There are two existing tests that seem to fail. 
These should be fixed in a separate PR.

**Review by Dref360 — APPROVED** [review]
LGTM

**Pull request merged**
