### PR TITLE
Add sort and drop_duplicates option to DataFrameIterator

### PR DESCRIPTION
**Pull request by smurak**
### Summary

Add "sort" and "drop_duplicates" option to DataFrameIterator to be able to generate data according to just as the input dataframe order.

### Related Issues

#72

### PR Overview

- [x] This PR requires new unit tests [y/n] (make sure tests are included)
- [x] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by Vijayabhaskar96** [comment]
@smurak @Dref360 Looks good.

**Comment by Dref360** [comment]
Is it right that sort and drop_duplicate are True by default? Would the user expect that?

**Comment by dzhus** [comment]
It's effectively the current behaviour. It's not obvious but probably makes sense for what ImageDataGenerator would be typically used for.

**Comment by Dref360** [comment]
All good LGTM

**Pull request merged**
