### PR TITLE
Fix Tokenizer init

### LINKED ISSUE #105: Tokenizer should always initialize document_count with zero
In the `Tokenizer` class, currently `self.document_count` is initialized with the argument `document_count`, but it should always be initialized with `0`. Allowing the user to initialize it with a non-zero value will result in incorrect results or errors in tf-idf mode. Furthermore, the `document_count` argument is not documented.

### PR DESCRIPTION
**Pull request by soroushj**
Remove the `document_count` arg, always initialize with 0.

### Summary
In the `Tokenizer` class, `self.document_count` was initialized with the argument `document_count`. This PR removes the argument and initializes `self.document_count` with `0`. Allowing users to pass non-zero values to `document_count` could cause incorrect results or errors in tf-idf mode. Also, this argument was not documented.

### Related Issues
Fixes #105

### PR Overview

- [n] This PR requires new unit tests [y/n] (make sure tests are included)
- [n] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by soroushj** [comment]
If we want to keep the API compeletely backward compatibile, I can modify the code to accept and ignore the `document_count` argument and throw a deprecation warning. Anyway, I think it's not a serious issue here, because the argument was not documented and probably not a ton of people were actually using it.

**Comment by soroushj** [comment]
Hi @qmeeus,
Thank you for reviewing the PR.
The issue you mentioned was introduced in the [second commit](https://github.com/keras-team/keras-preprocessing/pull/106/commits/8daeca4eaddd2f42f9453860d5ad4d3b5f9cc39f) and fixed in the [third commit](https://github.com/keras-team/keras-preprocessing/pull/106/commits/af5bf7e2063b351a2f3c80b70e6aaea4507c1ca2). As a result, the [final changes](https://github.com/keras-team/keras-preprocessing/pull/106/files) do not include this error and the final commit has passed the tests.

**Comment by qmeeus** [comment]
My bad, sorry about that :)

**Comment by fchollet** [comment]
I don't think the `document_count` argument serves a purpose as a user-settable constructor argument. There is no use case for changing the value by hand.

However, because we use it in TF-IDF computation (and only there) it is part of the state of the `Tokenizer` and it should be saved/loaded during serialization. Removing the argument entirely isn't correct for use cases when ones tries to use TF-IDF after loading a saved `Tokenizer`.

So I think we should move this arg to `**kwargs` like we do for some private layer arguments. That way, it isn't exposed to users, it isn't documented, but it's still saved as part of a serialized Tokenizer.

**Comment by soroushj** [comment]
Hey @fchollet, thank you for your comment.

This PR takes care of saving/loading `document_count` during serialization (see lines [501](https://github.com/keras-team/keras-preprocessing/pull/106/files#diff-25002d783a7458a5113a2a3807523c30R501) and [512](https://github.com/keras-team/keras-preprocessing/pull/106/files#diff-25002d783a7458a5113a2a3807523c30R512) of the diff). This is achieved without using `kwargs`—the `document_count` field is directly set during loading.

I think this is a better solution compared to using `kwargs`, because (1) it is consistent with the rest of implementation, i.e., saving/loading of other internal states such as `word_counts`; and (2) it does not change the current behavior of throwing an error for any kwarg except for `nb_words`, which is a deprecated name for `num_words`.

What do you think?

**Comment by soroushj** [comment]
Hey @fchollet, have you had time to look into this?

**Comment by soroushj** [comment]
Opened another PR, #313, that moves the `document_count` argument to `**kwargs` instead of removing it. We can merge one of these PRs and close the other one.

**Comment by soroushj** [comment]
Closing this PR because #313 is merged.

**Pull request closed without merging**
