### PR TITLE
Delete test_documentation.py

### PR DESCRIPTION
**Pull request by rragundez**
### Summary
Remove unused test for documentation. Keras preprocessing does not manage documentation itself.

### CODE REVIEW

**Comment by Dref360** [comment]
Even if we don't manage the doc, I think it is valuable to keep the same document format as Keras.

**Comment by rragundez** [comment]
I think it might be valuable to also test documentation, similar to: https://github.com/keras-team/keras/blob/master/tests/docs/test_documentation.py
What do you think?

**Comment by Dref360** [comment]
I agree, do you want to do it? Otherwise I'll do it this week.

**Comment by rragundez** [comment]
Would be great if you can give me a hand. If there are many test failing because of this I can help shaping the docs to what it supposed to be :), I'll close this PR then.

**Pull request closed without merging**
