### PR TITLE
List valid filenames in directory efficiency

### PR DESCRIPTION
**Pull request by itaihay**
### Summary
In the utils._list_valid_filenames_in_directory function, when providing a 'split' tuple, the functions calls the list() function twice: once with the len() function and another to save the split list.

This PR changes the code so that the list would just be saved beforehand. 
A little change for better readability and efficiency
### PR Overview

- [ ] This PR requires new unit tests [n] (make sure tests are included)
- [ ] This PR requires to update the documentation [n] (make sure the docs are up-to-date)
- [ ] This PR is backwards compatible [y]
- [ ] This PR changes the current API [n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by itaihay** [comment]
Hi guys. This is my first public PR ever so please let me know if there are any newcomer problems with it. It's quite simple so I hope everything is good.

**Comment by Dref360** [comment]
Hello!
You have some PEP8 errors. 
To find them you can run `py.test --pep8 -m pep8`
See our contribution guidelines: https://github.com/keras-team/keras-preprocessing/blob/master/CONTRIBUTING.md

**Comment by itaihay** [comment]
> Hello!
> You have some PEP8 errors.
> To find them you can run `py.test --pep8 -m pep8`
> See our contribution guidelines: https://github.com/keras-team/keras-preprocessing/blob/master/CONTRIBUTING.md

Hello Frédéric, thank you for the reply.
The PEP8 issue is now corrected.

**Comment by itaihay** [comment]
@Dref360 Passed the testing

**Pull request merged**
