### PR TITLE
Fix `transform_matrix_offset_center`

### PR DESCRIPTION
**Pull request by kshramt**
### Summary

Fix the axis of rotation, which has been shifted 1px from the correct location.

### PR Overview

- [x] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by rragundez** [comment]
@kshramt please provide an explanation of the PR, thanks.

**Comment by kshramt** [comment]
Thank you for the comment. I updated Summary.

**Comment by rragundez** [comment]
@kshramt thanks for the update. Can you explain further? provide an example that shows the current issue and how your change solves it. Are there any caveats to this change?

**Comment by kshramt** [comment]
> provide an example that shows the current issue and how your change solves it.

Please see the example at https://github.com/keras-team/keras-preprocessing/blob/436bf578bcc4ebd05d1ab563521a8c28096cc6e6/tests/image/affine_transformations_test.py#L30-L38 .

**Comment by rragundez** [comment]
the calculation `float(x) / 2 + 0.5` is the correct one. I do like the test you introduced though.

**Pull request closed without merging**
