### PR TITLE
Adding secure_image.py for supporting training on encrypted images.

### PR DESCRIPTION
**Pull request by akshaybahadur21**
### Summary
I have added support for encrypting directory of image and then write a generator for training the model on the encrypted model.
Adding the link to collab repo as well as a standalone package for the same.
### PR Overview

- [ n] This PR requires new unit tests [y/n] (make sure tests are included)
- [ yes ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [ y] This PR is backwards compatible [y/n]
- [ n] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by akshaybahadur21** [comment]
@rragundez - Can you please review?

**Comment by rragundez** [comment]
@akshaybahadur21 thanks for your PR, i quickly reviewed it, but my question is what is this solving? Your code seems a generic function to encrypt files, and I don't see how is related to Keras functionality. The best would have been to create an issue and see if your idea gets some traction, before doing all the effort.  

For example, I don't see why Keras would care about encrypting files, reading from encrypted files maybe, which means I would think a better approach would have been to implement something in the `load_img` function. Still I would like to see that this solves a current problem in the community, which I currently don't.

**Comment by akshaybahadur21** [comment]
@rragundez - Thanks for taking a look at my PR.
This functionality is for training on the cloud or data centers. You can read more about it.
I have created an add on library as well.
My idea was to create a `fit_generator` to decrypt and yield these images that the actual images are not stored on the cloud.
You can read more here : https://github.com/akshaybahadur21/keras-secure-image

**Comment by rragundez** [comment]
I understand what it achieves, but I don't see why Keras would care about encrypting images. That has nothing to do with what Keras is for, and also the user should be the one responsible to encrypting the images as he sees fit. Which means no decryption function can be written since it will have to address all possible ways. Therefore the only possible addition that I might see useful is modifying `load_img`, specifically this line https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/utils.py#L110
To allow the user to send whatever function wanted for reading images, included decryption.

**Comment by akshaybahadur21** [comment]
@rragundez - Oh.
Yes, I get your point now.
Let me make the changes and raise another request.

**Pull request closed without merging**
