### PR TITLE
Dictionary iterator

### PR DESCRIPTION
**Pull request by rragundez**
### Summary
This PR adds a `DictionaryIterator` class and `flow_from_dictionary` method. This class is quite flexible as it allows to send full-paths without relative to a directory parameters. Which will allow to fetch images from different root directories. The next step is to leverage this flexible API to include multi-output batches that match the functional Keras API and the multi-label one. Some of the internal logic has also been simplified in comparison with `DataframeIterator` (which in my opinion should be deprecated for several reasons, one of the main ones a dependency on the Pandas API which has substantially changed in the past).

I imagine having the well known `DirectoryIterator` for the already known simple use cases and `DictionaryIterator` for the more advance ones because of flexibility.

### PR Overview

- [y ] This PR requires new unit tests [y/n] (make sure tests are included)
- [y] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [y] This PR is backwards compatible [y/n]
- [n] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by Dref360** [comment]
I think we will stick with the Pandas API because it's widely used in the scientific community. If their API does changes, we will set a hard dependency version.

Since the `flow_from_dataframe` is pretty flexible already, I don't think we should merge your PR.

**Comment by rragundez** [comment]
@Dref360 OK I understand your point. I want to point out that normally when a Pandas dependency is added to an ML library is as an add-on feature. It normally first implemented with native Python code and data structures as the base, only after the add-on to support an external widely use library like Pandas is added, but rarely for mature library is the default way to go to use an external library. You can see that in the scikit packages for example. In general I don't think is a good practice to leave your core functionality to an external library.  For example I do not see a Pandas dependency in the complete Keras source code (no import but also no `DataFrame` method) but maybe I'm wrong. So I do not know the stands of @fchollet on this but perhaps it won't be easy to merge `DataFrameIterator` into the Keras source code. 

Have said that I understand your point and I'll concentrate then on updating the code in the DataframeIterator. Thanks for the feedback. Hopefully I can get to the multi-label and multi-output use cases before new years. Thanks again.

**Comment by Dref360** [comment]
1. Pandas is used inside keras codebase as a soft deps.
 i. https://github.com/keras-team/keras/blob/0cfa5c2709906a7a76f552f71a562f899e408695/keras/engine/training_utils.py#L33

2. `but perhaps it won't be easy to merge DataFrameIterator into the Keras source code`
 i. I'm not sure to get what you mean. keras-preprocessing is a standalone package that won't get merged into Keras.

As for this PR, I don't think we will merge it because the DataframeIterator should be the "standard" way of handling anything that cannot be done with flow_from_directory.

I would still like @fchollet input on that feature to be sure.

**Comment by rragundez** [comment]
I mean merged into: https://github.com/keras-team/keras/blob/master/keras/preprocessing/image.py like `DirectoryIterator` and `ImageDataGenerator`. I guess the integration there is the final step for a mature implementation. 

I agree with you @Dref360 that there should be preferably one way to deal with something that is not done by the `flow_from_directory`. So I started efforts to update `DataFrameIterator`.

**Comment by Dref360** [comment]
We should revisit the file you linked, I don't think it's useful anymore.

________________________________
De : rragundez <notifications@github.com>
Envoyé : 30 décembre 2018 12:01:33
À : keras-team/keras-preprocessing
Cc : Frédéric Branchaud-Charron; Mention
Objet : Re: [keras-team/keras-preprocessing] Dictionary iterator (#118)


I mean merged into: https://github.com/keras-team/keras/blob/master/keras/preprocessing/image.py like DirectoryIterator and ImageDataGenerator. I guess the integration there is the final step for a mature implementation.

I agree with you @Dref360<https://github.com/Dref360> that there should be preferably one way to deal with something that is not done by the flow_from_directory. So I started efforts to update DataFrameIterator.

**Comment by rragundez** [comment]
I've added multi-ouput and multi-label support

**Comment by rragundez** [comment]
Since we are doing a lot of work on the `DataFrameIterator` which this PR added I think this PR feature is not relevant anymore.

**Pull request closed without merging**
