### PR TITLE
Fix a bug in DataFrameIterator when `directory` has subdirectories

### PR DESCRIPTION
**Pull request by smurak**
### Summary

Fix a bug in DataFrameIterator when `directory` has subdirectories

### Related Issues

#92

### PR Overview

- [x] This PR requires new unit tests [y/n] (make sure tests are included)
- [ ] This PR requires to update the documentation [y/n] (make sure the docs are up-to-date)
- [x] This PR is backwards compatible [y/n]
- [ ] This PR changes the current API [y/n] (all API changes need to be approved by fchollet)

### CODE REVIEW

**Comment by smurak** [comment]
@Vijayabhaskar96 Would you check this PR?

**Comment by Vijayabhaskar96** [comment]
@smurak This case can already be handled with absolute paths right? Anyway good to have this too. PR Looks Good to me. @Dref360

**Comment by smurak** [comment]
@Vijayabhaskar96 Thank you.

> This case can already be handled with absolute paths right?

Yes. Using absolute paths and setting `directory` to None can handle any situation.
This PR allows users to set `directory` as the base directory and  "filenames" as relative paths from it.

**Comment by Vijayabhaskar96** [comment]
@smurak since the PR is not yet closed can you update the docs for flow_from_dataframe as well?

**Comment by smurak** [comment]
> @smurak since the PR is not yet closed can you update the docs for flow_from_dataframe as well?

@Vijayabhaskar96 OK, I've updated the docs. Please check.

**Pull request merged**
